"""
trade_database.py — Persistent SQLite Database for Live System Trade Logging & Audit
Records every trade generated by the live scanner, tracks exact entry/exit prices,
calculates duration, gross P/L, brokerage/taxes, net in-pocket P/L, and provides
state persistence across server restarts.
"""

import os
import sqlite3
import threading
from datetime import datetime
from typing import Dict, List, Any, Optional
import pandas as pd

DB_FILE_PATH = os.path.join(os.path.dirname(__file__), "live_trades.db")
_db_lock = threading.Lock()


def get_db_connection() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_FILE_PATH, check_same_thread=False, timeout=10.0)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    """Initialize database tables and schema indexes."""
    with _db_lock:
        conn = get_db_connection()
        cursor = conn.cursor()

        # 1. Live Trades Table
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS live_trades (
            trade_id TEXT PRIMARY KEY,
            commodity_key TEXT NOT NULL,
            contract_name TEXT NOT NULL,
            direction TEXT NOT NULL,
            strategy_model TEXT NOT NULL,
            entry_time TEXT NOT NULL,
            entry_spot REAL NOT NULL,
            entry_premium REAL NOT NULL,
            sl_pts REAL NOT NULL,
            sl_premium REAL NOT NULL,
            t1_pts REAL NOT NULL,
            t1_premium REAL NOT NULL,
            t2_pts REAL NOT NULL,
            t2_premium REAL NOT NULL,
            lots INTEGER NOT NULL,
            lot_size INTEGER NOT NULL,
            lot_unit TEXT NOT NULL,
            status TEXT NOT NULL,
            exit_time TEXT,
            exit_premium REAL,
            duration_str TEXT,
            points_captured REAL DEFAULT 0.0,
            gross_pnl_rs REAL DEFAULT 0.0,
            charges_rs REAL DEFAULT 0.0,
            net_pnl_rs REAL DEFAULT 0.0,
            outcome TEXT DEFAULT 'OPEN',
            notes TEXT DEFAULT ''
        )
        """)

        # 2. Daily Trade Limits Table
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS daily_trade_state (
            trade_date TEXT NOT NULL,
            commodity_key TEXT NOT NULL,
            trades_count INTEGER DEFAULT 0,
            PRIMARY KEY (trade_date, commodity_key)
        )
        """)

        conn.commit()
        conn.close()


def log_trade_entry(
    trade_id: str,
    commodity_key: str,
    contract_name: str,
    direction: str,
    strategy_model: str,
    entry_spot: float,
    entry_premium: float,
    sl_pts: float,
    sl_premium: float,
    t1_pts: float,
    t1_premium: float,
    t2_pts: float,
    t2_premium: float,
    lots: int,
    lot_size: int,
    lot_unit: str = "shares",
    entry_time: str = "",
    notes: str = ""
) -> bool:
    """Insert a newly fired live trade into persistent database."""
    if not entry_time:
        entry_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with _db_lock:
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute("""
            INSERT OR REPLACE INTO live_trades (
                trade_id, commodity_key, contract_name, direction, strategy_model,
                entry_time, entry_spot, entry_premium, sl_pts, sl_premium,
                t1_pts, t1_premium, t2_pts, t2_premium, lots, lot_size,
                lot_unit, status, outcome, notes
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'OPEN', 'OPEN', ?)
            """, (
                trade_id, commodity_key, contract_name, direction, strategy_model,
                entry_time, entry_spot, entry_premium, sl_pts, sl_premium,
                t1_pts, t1_premium, t2_pts, t2_premium, lots, lot_size,
                lot_unit, notes
            ))
            conn.commit()
            conn.close()
            return True
        except Exception as e:
            print(f"[TradeDB] Error logging trade entry {trade_id}: {e}")
            return False


def log_trade_event(
    trade_id: str,
    event_type: str,
    exit_premium: float,
    points_captured: float,
    gross_pnl_rs: float,
    charges_rs: float,
    net_pnl_rs: float,
    exit_time: str = "",
    notes: str = ""
) -> bool:
    """Update trade status, duration, and P/L upon Target, SL, or Breakeven exit."""
    if not exit_time:
        exit_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with _db_lock:
        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            # Retrieve entry time to calculate exact duration
            cursor.execute("SELECT entry_time FROM live_trades WHERE trade_id = ?", (trade_id,))
            row = cursor.fetchone()
            duration_str = "0m"
            if row and row["entry_time"]:
                try:
                    e_dt = datetime.strptime(row["entry_time"], "%Y-%m-%d %H:%M:%S")
                    x_dt = datetime.strptime(exit_time, "%Y-%m-%d %H:%M:%S")
                    sec = max(0, int((x_dt - e_dt).total_seconds()))
                    hrs, rem = divmod(sec, 3600)
                    mins, s = divmod(rem, 60)
                    if hrs > 0:
                        duration_str = f"{hrs}h {mins}m"
                    elif mins > 0:
                        duration_str = f"{mins}m {s}s"
                    else:
                        duration_str = f"{s}s"
                except Exception:
                    pass

            outcome_map = {
                "TARGET1": "PARTIAL_WIN (T1)",
                "TARGET2": "WIN (T2 Met)",
                "TRAIL_COST_EXIT": "BREAKEVEN",
                "STOP_LOSS": "LOSS (SL Hit)",
                "EOD_CLOSE": "EOD_SQUAREOFF"
            }
            outcome_val = outcome_map.get(event_type, event_type)

            cursor.execute("""
            UPDATE live_trades SET
                status = ?,
                exit_time = ?,
                exit_premium = ?,
                duration_str = ?,
                points_captured = ?,
                gross_pnl_rs = ?,
                charges_rs = ?,
                net_pnl_rs = ?,
                outcome = ?,
                notes = CASE WHEN ? != '' THEN ? ELSE notes END
            WHERE trade_id = ?
            """, (
                event_type, exit_time, exit_premium, duration_str,
                points_captured, gross_pnl_rs, charges_rs, net_pnl_rs,
                outcome_val, notes, notes, trade_id
            ))
            conn.commit()
            conn.close()
            return True
        except Exception as e:
            print(f"[TradeDB] Error logging trade event {trade_id}: {e}")
            return False


def get_open_trades() -> List[Dict[str, Any]]:
    """Retrieve any open positions to resume tracking after server restart."""
    with _db_lock:
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM live_trades WHERE status = 'OPEN' OR status = 'TARGET1'")
            rows = cursor.fetchall()
            trades = [dict(r) for r in rows]
            conn.close()
            return trades
        except Exception as e:
            print(f"[TradeDB] Error reading open trades: {e}")
            return []


def get_daily_trade_count(commodity_key: str, trade_date: str) -> int:
    """Get persistent count of trades fired today for an asset."""
    with _db_lock:
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute("""
            SELECT trades_count FROM daily_trade_state 
            WHERE trade_date = ? AND commodity_key = ?
            """, (trade_date, commodity_key.upper().strip()))
            row = cursor.fetchone()
            count = int(row["trades_count"]) if row else 0
            conn.close()
            return count
        except Exception:
            return 0


def increment_daily_trade_count(commodity_key: str, trade_date: str):
    """Increment persistent daily trade count for an asset."""
    with _db_lock:
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute("""
            INSERT INTO daily_trade_state (trade_date, commodity_key, trades_count)
            VALUES (?, ?, 1)
            ON CONFLICT(trade_date, commodity_key) DO UPDATE SET
            trades_count = trades_count + 1
            """, (trade_date, commodity_key.upper().strip()))
            conn.commit()
            conn.close()
        except Exception as e:
            print(f"[TradeDB] Error incrementing daily count: {e}")


def get_live_trades_df(
    commodity_key: Optional[str] = None,
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    limit: int = 500
) -> pd.DataFrame:
    """Retrieve DataFrame of live trades for dashboard presentation."""
    with _db_lock:
        try:
            conn = get_db_connection()
            query = "SELECT * FROM live_trades WHERE 1=1"
            params = []

            if commodity_key and commodity_key != "ALL":
                query += " AND commodity_key = ?"
                params.append(commodity_key.upper().strip())

            if date_from:
                query += " AND entry_time >= ?"
                params.append(f"{date_from} 00:00:00")

            if date_to:
                query += " AND entry_time <= ?"
                params.append(f"{date_to} 23:59:59")

            query += " ORDER BY entry_time DESC LIMIT ?"
            params.append(limit)

            df = pd.read_sql_query(query, conn, params=params)
            conn.close()
            return df
        except Exception as e:
            print(f"[TradeDB] Error reading live trades DF: {e}")
            return pd.DataFrame()


def get_live_performance_summary(commodity_key: Optional[str] = None) -> Dict[str, Any]:
    """Aggregate total live system performance metrics."""
    df = get_live_trades_df(commodity_key=commodity_key, limit=1000)
    if df.empty:
        return {
            "total_signals": 0,
            "completed_trades": 0,
            "open_trades": 0,
            "winning_trades": 0,
            "losing_trades": 0,
            "win_rate": 0.0,
            "total_gross_pnl": 0.0,
            "total_charges": 0.0,
            "total_net_pnl": 0.0,
            "profit_factor": 0.0,
            "max_drawdown": 0.0
        }

    completed = df[df["status"].isin(["TARGET2", "STOP_LOSS", "TRAIL_COST_EXIT", "EOD_CLOSE"])]
    open_t = df[df["status"].isin(["OPEN", "TARGET1"])]
    
    total_signals = len(df)
    n_completed = len(completed)
    n_open = len(open_t)

    if n_completed == 0:
        return {
            "total_signals": total_signals,
            "completed_trades": 0,
            "open_trades": n_open,
            "winning_trades": 0,
            "losing_trades": 0,
            "win_rate": 0.0,
            "total_gross_pnl": 0.0,
            "total_charges": 0.0,
            "total_net_pnl": 0.0,
            "profit_factor": 0.0,
            "max_drawdown": 0.0
        }

    wins = completed[completed["net_pnl_rs"] > 0]
    losses = completed[completed["net_pnl_rs"] < 0]
    
    n_wins = len(wins)
    n_losses = len(losses)
    win_rate = round((n_wins / n_completed) * 100, 1) if n_completed > 0 else 0.0

    tot_gross = round(float(completed["gross_pnl_rs"].sum()), 2)
    tot_charges = round(float(completed["charges_rs"].sum()), 2)
    tot_net = round(float(completed["net_pnl_rs"].sum()), 2)

    gross_profit = float(wins["net_pnl_rs"].sum()) if not wins.empty else 0.0
    gross_loss = abs(float(losses["net_pnl_rs"].sum())) if not losses.empty else 0.0
    profit_factor = round(gross_profit / max(1.0, gross_loss), 2)

    # Max Drawdown
    cum_pnl = completed["net_pnl_rs"].iloc[::-1].cumsum()
    peak = cum_pnl.cummax()
    dd = peak - cum_pnl
    max_dd = round(float(dd.max()), 2) if not dd.empty else 0.0

    return {
        "total_signals": total_signals,
        "completed_trades": n_completed,
        "open_trades": n_open,
        "winning_trades": n_wins,
        "losing_trades": n_losses,
        "win_rate": win_rate,
        "total_gross_pnl": tot_gross,
        "total_charges": tot_charges,
        "total_net_pnl": tot_net,
        "profit_factor": profit_factor,
        "max_drawdown": max_dd
    }


# Auto-initialize database on import
init_db()
